import { bakeParametricScale } from '../src/core/ParametricScale.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { Profile } from '../src/entities/Profile.js';
import { Plate } from '../src/entities/Plate.js';
import { Fastener,FASTENER_METRICS } from '../src/entities/Fastener.js';
import { Reinforcement } from '../src/entities/Reinforcement.js';
import { Weld } from '../src/entities/Weld.js';
import { getProfileData, getSizes, SERIES_LIST } from '../src/entities/ProfileCatalog.js';
import { serializeProject, restoreProject } from '../src/core/ProjectSerializer.js';
import { buildSmartConnection, sectionFrame } from '../src/core/SmartConnection.js';
import { boltLayout,validatePolygon } from '../src/core/WorkshopGeometry.js';
import { surfaceDistance,solidRelation } from '../src/core/GeometryQueries.js';
import { PresetManager,STRUCTURE_PRESETS,CONNECTION_PRESETS } from '../src/presets/PresetManager.js';
import { drawingSVG } from '../src/core/WorkshopDrawing.js';
import {WORKSHOP_LESSONS} from '../src/presets/WorkshopCurriculum.js';

const near=(a,b,tol=1e-7)=>assert.ok(Math.abs(a-b)<=tol,`${a} != ${b} (tol ${tol})`);
const scene=()=>({scene:new THREE.Scene(),objects:[],addObject(o){this.objects.push(o);this.scene.add(o.mesh);},removeObject(o){this.objects.splice(this.objects.indexOf(o),1);this.scene.remove(o.mesh);}});
const node=(slope=0,rotation=0)=>{const c=new Profile('HEB','300',4,'column'),b=new Profile('IPE','300',2.8,'beam');c.setPosition(0,2,0);b.mesh.rotation.x=-slope*Math.PI/180;b.setPosition(0,2.4+Math.sin(slope*Math.PI/180)*1.4,.17+Math.cos(slope*Math.PI/180)*1.4);if(rotation){const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),rotation);for(const o of[c,b]){o.mesh.position.applyQuaternion(q);o.mesh.quaternion.premultiply(q);o.mesh.updateMatrixWorld(true);}}return{c,b};};
const finite=o=>o.mesh.traverse(m=>{if(m.isMesh)for(const v of m.geometry.attributes.position.array)assert.ok(Number.isFinite(v),o.designation);});

for(const[series,size]of[['IPE','300'],['HEB','300'],['HEA','200'],['IPN','200'],['UPN','200'],['L','80x8'],['SHS','100x100x5'],['CHS','76.1x3.6']])test(`Envolvente dimensional ${series} ${size}`,()=>{const p=new Profile(series,size,2.345,'beam'),d=getProfileData(series,size);assert.ok(d);const box=p.getBoundingBox().getSize(new THREE.Vector3());near(box.z,2.345,3e-7);near(box.y,(d.h||d.d||d.a)/1000,1e-5);finite(p);});

test('Editar conserva identidad, posición, rotación y escala',()=>{const p=new Profile('HEB','200',3,'column'),root=p.mesh;p.setPosition(1.123,2.456,3.789);p.setRotation(7,13,29);const q=p.mesh.quaternion.clone();p.mesh.scale.set(1,1,1.2);p.update({size:'300',length:2.001});assert.equal(p.mesh,root);assert.deepEqual(p.mesh.position.toArray(),[1.123,2.456,3.789]);near(p.mesh.quaternion.angleTo(q),0);assert.deepEqual(p.mesh.scale.toArray(),[1,1,1.2]);});
test('Polígonos y matrices rechazan geometría inválida',()=>{assert.throws(()=>validatePolygon([{x:0,y:0},{x:10,y:10},{x:0,y:10},{x:10,y:0}]));assert.throws(()=>boltLayout({width:80,height:80,diameter:24,edge:10,rows:4,cols:4}));assert.equal(boltLayout({width:300,height:500,diameter:20,edge:40,rows:4,cols:2}).points.length,8);});
for(const slope of[-15,0,15,30])for(const rotation of[0,Math.PI/4])test(`Unión ${slope}° / giro ${rotation.toFixed(2)}: tornillos, rigidizadores y plano de corte`,()=>{const{c,b}=node(slope,rotation),r=buildSmartConnection(c,b),plate=r.parts.find(p=>p.type==='plate'&&p.params.subtype==='endplate'),bolts=r.parts.filter(p=>p.type==='fastener'),stiff=r.parts.filter(p=>p.params.category==='stiffener');assert.equal(bolts.length,8);assert.equal(stiff.length,4);near(r.nominalStiffenerWidthMm,144.5);near(r.thicknessMm,10.7);const inv=plate.mesh.matrixWorld.clone().invert(),metric=FASTENER_METRICS.M20;for(const f of bolts){const nutWasher=f.mesh.children.find(m=>m.name==='Arandela bajo tuerca');const p=nutWasher.getWorldPosition(new THREE.Vector3()).applyMatrix4(inv);near(p.z+metric.washerT/2000,-plate.params.thickness/2-.019,1e-7);const headWasher=f.mesh.children.find(m=>m.name==='Arandela bajo cabeza');const h=headWasher.getWorldPosition(new THREE.Vector3()).applyMatrix4(inv);near(h.z-metric.washerT/2000,plate.params.thickness/2,1e-7);}for(const part of[c,b,...r.parts])finite(part);const length=b.params.length,r2=buildSmartConnection(c,b,r.config);near(length,b.params.length);assert.equal(c.params.drillings.length,8);assert.equal(r2.parts.length,r.parts.length);});
test('Holgura de 10 mm y contacto superficial',()=>{const a=new Plate('base',.2,.2,.01),b=new Plate('base',.2,.2,.01);b.setPosition(0,0,.02);near(surfaceDistance(a,b).distance,.01,1e-8);b.setPosition(.03,0,.01);near(surfaceDistance(a,b).distance,0,1e-8);});
test('Guardar y cargar mantiene piezas y medidas',()=>{const s=scene(),{c,b}=node(15);const joint=buildSmartConnection(c,b);for(const o of[c,b,...joint.parts,new Reinforcement({length:1.234,diameterMm:12}),new Weld(new THREE.Vector3(0,0,0),new THREE.Vector3(.1,0,0),.005)])s.addObject(o);const data=serializeProject(s.objects,{measurements:[{type:'distance',points:[[0,0,0],[.01,0,0]]}]}),target=scene();restoreProject(JSON.parse(JSON.stringify(data)),target);const second=serializeProject(target.objects);assert.equal(second.objects.length,data.objects.length);for(let i=0;i<data.objects.length;i++){assert.deepEqual(second.objects[i].position,data.objects[i].position);assert.deepEqual(second.objects[i].params,data.objects[i].params);finite(target.objects[i]);}assert.equal(data.units.display,'mm');});
for(const preset of[...STRUCTURE_PRESETS,...CONNECTION_PRESETS])test(`Plantilla ${preset.id}: generar, exportar y restaurar`,()=>{const s=scene(),pm=new PresetManager({sceneManager:s}),result=pm.generate(preset.id);assert.ok(result.length>0);result.forEach(finite);const target=scene();restoreProject(serializeProject(result),target);assert.equal(result.length,target.objects.length);target.objects.forEach(finite);});
test('Plano SVG exporta unidades, geometría y taladros',()=>{const p=new Plate('base',.3,.2,.012,{holes:[{x:.05,y:0,diameter:.022}]});const svg=drawingSVG(p);assert.match(svg,/<svg/);assert.match(svg,/mm/);assert.match(svg,/22/);assert.ok(!svg.includes('NaN'));});

for(const slope of[-30,-15,0,15,30])test(`Rigidizadores a ${slope}° libres de penetración en el pilar`,()=>{const{c,b}=node(slope),r=buildSmartConnection(c,b);for(const part of r.parts.filter(p=>p.params.category==='stiffener')){assert.equal(solidRelation(c,part).kind,'separated');assert.ok(surfaceDistance(c,part).distance>=.00049);}const plate=r.parts[0];assert.equal(solidRelation(plate,b).kind,'contact');});
test('Taladros: rechazar matriz exterior y regenerar sin duplicados',()=>{const s=scene(),p=new Plate('base',.3,.3,.012),pm=new PresetManager({sceneManager:s});s.addObject(p);assert.throws(()=>pm.generateBoltMatrix(p,{rows:6,cols:6,spacingX:.1,spacingY:.1}));assert.equal(s.objects.length,1);pm.generateBoltMatrix(p);assert.equal(s.objects.length,5);pm.generateBoltMatrix(p,{rows:2,cols:2,spacingX:.12,spacingY:.12});assert.equal(s.objects.length,5);assert.equal(p.params.holes.length,4);});
test('Distinguir una pieza embebida de una holgura',()=>{const a=new Plate('base',.3,.3,.1),b=new Plate('base',.1,.1,.01);assert.equal(solidRelation(a,b).kind,'penetration');b.setPosition(0,0,.2);assert.equal(solidRelation(a,b).kind,'separated');});
for(const lesson of WORKSHOP_LESSONS)test(`Aula ${lesson.id}: ${lesson.title}`,()=>{const s=scene(),pm=new PresetManager({sceneManager:s}),parts=pm.generate(lesson.preset,lesson.parameters);assert.ok(parts.length);parts.forEach(finite);assert.ok(lesson.slide>=1&&lesson.slide<=49);});

for(const series of SERIES_LIST)for(const size of getSizes(series))test(`Catálogo ${series} ${size}: crear y modificar`,()=>{const o=new Profile(series,size,1.2345,'beam'),d=getProfileData(series,size);assert.ok(o.mesh);finite(o);const box=o.getBoundingBox().getSize(new THREE.Vector3());near(box.z,1.2345,2e-7);near(box.y,(d.h||d.d||d.a)/1000,2e-6);o.update({length:2.0001});near(o.getBoundingBox().getSize(new THREE.Vector3()).z,2.0001,3e-7);});
test('Carga inválida no borra el proyecto abierto',()=>{const s=scene(),old=new Profile();s.addObject(old);assert.throws(()=>restoreProject({objects:[{type:'plate',params:{width:.2,height:.2,thickness:.01}},{type:'unknown'}]},s));assert.deepEqual(s.objects,[old]);assert.throws(()=>restoreProject({objects:[{type:'profile',params:{length:-1}}]},s));assert.deepEqual(s.objects,[old]);});
test('Identificadores repetidos se rechazan antes de mutar',()=>{const s=scene(),o=new Profile(),data=serializeProject([o,o]);s.addObject(o);assert.throws(()=>restoreProject(data,s));assert.deepEqual(s.objects,[o]);});
test('Escala longitudinal modifica la cota real del perfil',()=>{const p=new Profile('IPE','300',2,'beam');p.mesh.scale.z=1.25;bakeParametricScale(p);near(p.params.length,2.5);near(p.getBoundingBox().getSize(new THREE.Vector3()).z,2.5);p.mesh.scale.x=2;assert.throws(()=>bakeParametricScale(p));near(p.mesh.scale.x,1);});
test('Escala de chapa y taladros conserva dimensiones y circularidad',()=>{const p=new Plate('base',.2,.2,.01,{holes:[{x:0,y:0,diameter:.02}]});p.mesh.scale.set(2,2,1.5);bakeParametricScale(p);near(p.params.width,.4);near(p.params.thickness,.015);near(p.params.holes[0].diameter,.04);p.mesh.scale.x=2;assert.throws(()=>bakeParametricScale(p));});
test('Soldadura: garganta real y normales vinculadas al giro',()=>{const owner=new Plate('base',1,1,.01),a=new THREE.Vector3(0,0,0),b=new THREE.Vector3(.1,0,0),w=new Weld(a,b,.005,{a:{objectId:owner.id,localPoint:a.toArray()},b:{objectId:owner.id,localPoint:b.toArray()}});w.setSectionNormals(new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1),[owner,owner]);const box=w.getBoundingBox().getSize(new THREE.Vector3());near(box.y,.005*Math.SQRT2,1e-7);near(box.z,.005*Math.SQRT2,1e-7);owner.setRotation(0,90,0);w.updateFromBindings(id=>owner);near(w.pointB.z,-.1);near(new THREE.Vector3(...w.params.surfaceNormals[1]).x,1);finite(w);});
for(const preset of[...STRUCTURE_PRESETS,...CONNECTION_PRESETS])test(`Sin penetraciones entre perfiles y chapas: ${preset.id}`,()=>{const s=scene(),parts=new PresetManager({sceneManager:s}).generate(preset.id).filter(o=>o.type!=='fastener');for(let i=0;i<parts.length;i++)for(let j=0;j<i;j++){const a=parts[i],b=parts[j];if(!a.getBoundingBox().intersectsBox(b.getBoundingBox()))continue;assert.notEqual(solidRelation(a,b).kind,'penetration',a.params.role+' / '+b.params.role);}});
test('Rechazar taladros por encima del pilar',()=>{const{c,b}=node();b.setPosition(0,3.98,1.57);assert.throws(()=>buildSmartConnection(c,b),/extremo del pilar/);});
test('Huecos poligonales del plano no generan NaN',()=>{const p=new Plate('gusset-square',1,1,.01,{holes:[{points:[{x:-.1,y:-.1},{x:.1,y:-.1},{x:0,y:.1}]}]});assert.ok(!drawingSVG(p).includes('NaN'));});
