import { icon } from './icons.js';
import { categoryOf,escapeHTML as esc } from '../core/WorkshopGeometry.js';

const GROUPS=[['profile','Perfiles'],['plate','Chapas y cartelas'],['stiffener','Rigidizadores'],['fastener','Tornillería'],['weld','Soldaduras'],['floor','Forjados'],['reinforcement','Armaduras']];
export class Sidebar {
  constructor(el){this.el=el;this.callbacks={};this._objects=[];this.collapsed=new Set();this.projectName='Sin título';this.render();}
  on(a,cb){this.callbacks[a]=cb;}
  _emit(a,p){this.callbacks[a]?.(p);}
  render(){this.el.innerHTML=`<section class="model-browser"><header class="model-browser__header"><span>MODELO DE TALLER</span><button data-collapse title="Contraer navegador">‹</button></header><label class="model-search">${icon('search',13)}<input type="search" placeholder="Buscar pieza, nombre o ID…" aria-label="Buscar en el modelo"></label><div class="workshop-model-heading"><b data-project></b><small data-count></small></div><details class="workshop-tree-views"><summary>Vistas y secciones</summary><div>${[['view-iso','Perspectiva'],['view-top','Planta'],['view-front','Alzado frontal'],['view-back','Alzado posterior'],['view-left','Alzado izquierdo'],['view-right','Alzado derecho'],['section-x','Corte X'],['section-y','Corte Y'],['section-z','Corte Z']].map(([a,l])=>`<button data-action="${a}">${l}</button>`).join('')}</div></details><div class="model-tree" data-tree></div></section>`;this.el.querySelector('[data-collapse]').onclick=()=>{document.documentElement.classList.toggle('model-browser-collapsed');window.dispatchEvent(new Event('resize'));};this.el.querySelector('input').oninput=()=>this.refresh();this.el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>this._emit(b.dataset.action));}
  refresh(objects=this._objects){this._objects=objects;const query=this.el.querySelector('input').value.toLowerCase(),filtered=objects.filter(o=>`${o.designation} ${o.params.role||''} ${o.id}`.toLowerCase().includes(query));this.el.querySelector('[data-project]').textContent=this.projectName;this.el.querySelector('[data-count]').textContent=`${objects.length} piezas · ${objects.filter(o=>o.mesh.visible).length} visibles`;const tree=this.el.querySelector('[data-tree]');tree.innerHTML=objects.length?GROUPS.map(([key,label])=>{const items=filtered.filter(o=>categoryOf(o)===key);if(!items.length)return'';return`<details data-group="${key}" ${this.collapsed.has(key)?'':'open'}><summary>${label}<small>${items.length}</small></summary>${items.map(o=>`<button class="tree-object ${o._isSelected?'selected':''}" data-id="${esc(o.id)}"><span>${esc(o.params.role||o.designation)}</span><small>${esc(o.id)} · ${esc(o.designation)}</small></button>`).join('')}</details>`;}).join(''):'<div class="workshop-empty-model"><b>Empieza por una pieza</b><p>Elige un perfil o abre una práctica del aula.</p><span>Arrastrar: orbitar<br>Botón derecho: desplazar<br>Rueda: zoom al cursor<br>Doble clic: centro de giro</span></div>';tree.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>this._emit('select-object',b.dataset.id));tree.querySelectorAll('details').forEach(d=>d.ontoggle=()=>d.open?this.collapsed.delete(d.dataset.group):this.collapsed.add(d.dataset.group));}
  setActiveObject(id){this.el.querySelectorAll('[data-id]').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));}
  setActiveTool(){}
}
