import { icon } from './icons.js';
const groups = {
  modelo: [['Perfiles I / H', [['add-heb-col','column','HEB'],['add-hea-col','column','HEA'],['add-ipe','beam','IPE'],['add-ipn','beam','IPN'],['add-heb-beam','beam','Viga HEB']]],['Secciones', [['add-upn','beam','UPN'],['add-chs','circle','Circular'],['add-shs','plate','Cuadrado'],['add-angle','angle','Angular L']]],['Modelado',[['tool-select','pointer','Seleccionar'],['open-custom-part','layers','Pieza libre']]]],
  conexiones: [['Uniones', [['smart-connection','wand','Unión inteligente'],['preset-connections','plate','Biblioteca'],['bolt-matrix','arrayLinear','Matriz N × M']]],['Chapas', [['add-plate','plate','Placa base'],['add-gusset-sq','plate','Cartela □'],['add-gusset-tri','angle','Cartela △'],['add-cleat','angle','Casquillo L'],['add-neoprene','plate','Neopreno']]],['Montaje',[['add-bolt','bolt','Tornillo'],['add-nut','bolt','Tuerca'],['add-washer','circle','Arandela'],['add-anchor','bolt','Anclaje'],['tool-weld','weld','Soldadura']]]],
  estructura: [['Biblioteca constructiva',[['preset-structures','wand','Estructuras'],['preset-portal','column','Pórtico'],['preset-truss','truss','Cercha']]],['Forjados',[['floor-slab','plate','Losa'],['floor-deck','layers','Chapa'],['floor-mesh','arrayLinear','Malla'],['floor-negative','angle','Armadura']]],['Conjuntos',[['explode-assembly','layers','Despiece'],['clash-scan','warning','Interferencias']]]],
  edicion: [['Transformar',[['tool-select','pointer','Seleccionar'],['tool-move','move','Mover'],['tool-rotate','rotate','Rotar'],['duplicate','copy','Duplicar'],['delete-selected','trash','Eliminar']]],['Repetir',[['array-linear','arrayLinear','Matriz lineal'],['array-polar','rotate','Matriz polar']]],['Referencias',[['coord-space-world','cube','Global'],['coord-space-local','cube','Local'],['toggle-snap','crosshair','Capturas'],['show-all','eye','Mostrar todo']]]],
  informes: [['Medición en mm',[['measure-dist','ruler','Distancia'],['measure-angle','angle','Ángulo'],['measure-area','plate','Área'],['check-clearance','ruler','Holgura']]],['Documentación',[['workshop-drawing','file','Plano de taller'],['capture-png','camera','Captura PNG'],['export-json','download','Proyecto']]],['Proyección',[['view-iso','cube','3D'],['view-top','viewTop','Planta'],['view-front','viewFront','Alzado'],['view-right','viewFront','Perfil'],['section-cut','layers','Sección']]]],
  aula: [['Aprender y construir',[['open-tutorial','graduation','Aula ETSIE'],['preset-connections','plate','Detalles'],['preset-structures','truss','Tipologías']]],['Visualización',[['mode-clay','circle','Color plano'],['mode-wire','cube','Aristas'],['mode-xray','layers','Transparencia']]]],
};
export class Ribbon {
  constructor(el){this.ribbon=el;this.callbacks={};this._render();}
  on(action,cb){this.callbacks[action]=cb;}
  _emit(action){this.callbacks[action]?.();}
  _render(){
    const tabs={modelo:'PERFILES',conexiones:'UNIONES',estructura:'ESTRUCTURAS',edicion:'EDITAR',informes:'TALLER',aula:'AULA'};
    this.ribbon.innerHTML=`<div class="ribbon-tabs" role="tablist">${Object.entries(tabs).map(([key,name],i)=>`<button class="ribbon-tab ${!i?'active':''}" data-tab="${key}" role="tab" aria-selected="${!i}">${name}</button>`).join('')}<span class="workshop-ribbon-note">TALLER · mm</span></div><div class="ribbon-content">${Object.entries(groups).map(([key,sections],i)=>`<div class="ribbon-panel ${i?'hidden':''}" data-panel="${key}">${sections.map(([name,buttons])=>`<div class="ribbon-group-box"><div class="ribbon-group-buttons">${buttons.map(([action,glyph,label])=>`<button class="ribbon-btn" data-action="${action}" title="${label}" aria-label="${label}">${icon(glyph,22)}<span>${label}</span></button>`).join('')}</div><div class="ribbon-group-title">${name}</div></div>`).join('')}</div>`).join('')}</div>`;
    this.ribbon.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.ribbon.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-selected',String(t===b));});this.ribbon.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.tab));});
    this.ribbon.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>this._emit(b.dataset.action));
  }
  setActiveButton(action){this.ribbon.querySelectorAll('[data-action^="tool-"]').forEach(b=>b.classList.toggle('active',b.dataset.action===action));}
  setActiveModeButton(mode){this.ribbon.querySelectorAll('[data-action^="mode-"]').forEach(b=>b.classList.toggle('active',b.dataset.action===`mode-${mode}`));}
}
