// Exercises are editable workshop models, not dimensional replicas of a photograph.
// Source deck reviewed: 20250714_CIV_L3_SISTEMAS ESTRUCTURALES, 49 slides.
const row=(title,preset,parameters,slide,objective)=>({title,preset,parameters,slide,objective});
export const WORKSHOP_LESSONS=[
 row('Placa base y anclajes','baseplate-rigid',{columnSize:'200',plateWidth:.4},3,'Medir la salida de placa y revisar la accesibilidad a tuercas.'),
 row('Pórtico y encuentro de cumbrera','portal-duopitch',{span:8,height:4,slope:15},7,'Comparar extremos del dintel, pendiente y eje de cumbrera.'),
 row('Junta de dilatación','expansion-joint-frame',{gap:.05},40,'Medir 50 mm de separación libre entre las alineaciones.'),
 row('Cercha: cordones y diagonales','truss',{span:12,height:2.4,panels:8},31,'Identificar cordones, montantes y cartelas. Revisar cada encuentro.'),
 row('Extremo de cercha','truss',{span:8,height:1.6,panels:6},31,'Estudiar el apoyo, el primer montante y la cartela extrema.'),
 row('Viga alveolar','castellated-beam',{span:5},32,'Medir los huecos y distinguir alma y alas continuas.'),
 row('Apoyo mediante casquillos','double-cleat',{metric:'M16',cleatHeight:.22},17,'Revisar apoyo, caras de contacto y acceso de montaje.'),
 row('Empalme con cubrejuntas','beam-splice',{beamSize:'240'},23,'Medir holgura entre extremos y alinear cubrejuntas.'),
 row('Viga–pilar con testa','endplate-rigid',{beamSize:'300',columnSize:'300'},25,'Comprobar testa, taladros y rigidizadores en las alas de la viga.'),
 row('Forjado con conectores','steel-deck-studs',{width:3,length:4},8,'Identificar la chapa, las vigas y la base de los conectores.'),
 row('Viga alveolar: variación de canto','castellated-beam',{span:6,beamDepth:.6},32,'Comparar geometrías de huecos sin invadir las alas.'),
 row('IPE 330 sobre pilar HEB','endplate-rigid',{beamSize:'330',columnSize:'300'},26,'Examinar la diferencia de canto y la continuidad de rigidizadores.'),
 row('Empalme de IPE 330','beam-splice',{beamSize:'330'},23,'Localizar tornillos y medir las distancias entre ejes.'),
 row('Encuentro de extremo','endplate-rigid',{beamSize:'300',columnSize:'280'},27,'Seguir el orden pilar, testa, viga, fijaciones y refuerzos.'),
 row('Apoyo y cartela de asiento','double-cleat',{cleatHeight:.18},14,'Comparar la superficie de apoyo y el plano del alma.'),
 row('Base: variante de pernos','baseplate-rigid',{metric:'M24',plateWidth:.45,columnSize:'200'},3,'Comprobar agujero, arandela, tuerca y separación del pilar.'),
 row('Soporte compuesto','composite-column-batten',{height:4},19,'Medir separación de canales y paso de las presillas.'),
 row('Viga IPE 240 y pilar','endplate-rigid',{beamSize:'240',columnSize:'300'},25,'Observar cómo cambian testa y rigidizadores con la sección.'),
 row('Viga IPE 400 y pilar','endplate-rigid',{beamSize:'400',columnSize:'300'},26,'Revisar canto proyectado, cartela y distancias a borde.'),
 row('Nudo inferior de cercha','truss',{span:10,height:2,panels:8},31,'Separar visualmente diagonales, cordón y cartela.'),
 row('Presillas y montaje','composite-column-batten',{height:3},20,'Dibujar el despiece y comprobar los contactos de las presillas.'),
 row('Planta de un pórtico','portal-flat',{span:6,height:3},8,'Usar planta ortográfica y medir los ejes de los pilares.'),
 row('Viga alveolar: distribución','castellated-beam',{span:8},32,'Comparar separación y repetición de huecos.'),
 row('Nudo con vigas opuestas','rigid-haunched-node',{columnSize:'300',beamSize:'270'},28,'Examinar las dos caras del pilar y la continuidad interior.'),
 row('Arranque de pilar','baseplate-rigid',{columnSize:'260',plateWidth:.5},49,'Estudiar placa, anclajes y acceso a soldaduras.'),
 row('Doble angular de alma','double-cleat',{metric:'M20',cleatHeight:.25},17,'Revisar ambas caras del alma y los agujeros coincidentes.'),
 row('Continuidad con IPE 240','rigid-haunched-node',{beamSize:'240',columnSize:'300'},29,'Comparar cartelas simétricas y ejes de ambas vigas.'),
 row('Continuidad con IPE 400','rigid-haunched-node',{beamSize:'400',columnSize:'300'},29,'Examinar cambios de espesor y dimensiones de la unión.'),
 row('Dos alineaciones en cimentación','expansion-joint-frame',{gap:.1},49,'Distinguir junta del entramado y disposición de bases.'),
 row('Vano arriostrado','braced-bay-x',{span:6,height:4},35,'Revisar los extremos de diagonales y sus cartelas.'),
 row('Forjado interior','steel-deck-studs',{width:4,length:6},8,'Medir canto de greca, separación de vigas y conectores.'),
 row('Pórtico de cubierta: variación de pendiente','portal-duopitch',{span:10,height:5,slope:25},7,'Verificar aleros, cumbrera y continuidad de los cortes.'),
].map((item,i)=>({...item,id:i+1,referenceStatus:'Modelo de práctica paramétrico; contraste dimensional con el original pendiente.'}));
