import * as THREE from 'three';
import { PresetManager } from '../presets/PresetManager.js';
import { ClashDetector } from './ClashDetector.js';
import { Profile } from '../entities/Profile.js';
import { Plate } from '../entities/Plate.js';
import { FASTENER_METRICS } from '../entities/Fastener.js';
import { Reinforcement } from '../entities/Reinforcement.js';
import { serializeBIMObject, createBIMObjectFromState } from './ProjectSerializer.js';
import { findEncounter, buildSmartConnection } from './SmartConnection.js';
import { surfaceDistance, solidRelation } from './GeometryQueries.js';
import { showDrawing } from './WorkshopDrawing.js';
import { escapeHTML as esc } from './WorkshopGeometry.js';

const cloneObject=o=>{const c=createBIMObjectFromState(serializeBIMObject(o));c.mesh.position.copy(o.mesh.position);c.mesh.quaternion.copy(o.mesh.quaternion);c.mesh.scale.copy(o.mesh.scale);c.mesh.updateMatrixWorld(true);return c;};
export class ProWorkspaceController {
  constructor(options){Object.assign(this,options);this.exploded=new Map();this.clashDetector=new ClashDetector(this.sceneManager,{tolerance:.0001,excludeSameConnection:false});this.presetManager=new PresetManager({sceneManager:this.sceneManager,getSelected:()=>this.getSelected(),onSelect:o=>this.selectObject(o),onCommit:()=>{this.pushUndo();this.refresh();},toast:this.toast});}
  wire(){
    const on=(name,cb)=>this.ribbon.on(name,cb);
    on('preset-structures',()=>this.presetManager.open('structure'));on('preset-portal',()=>this.presetManager.open('structure','portal-duopitch'));on('preset-truss',()=>this.presetManager.open('structure','truss'));on('preset-connections',()=>this.presetManager.open('connection'));
    on('bolt-matrix',()=>this.presetManager.openBoltMatrix());on('smart-connection',()=>this.openSmartConnection());on('explode-assembly',()=>this.toggleExploded(this.getSelected()));on('clash-scan',()=>this.scanClashes());on('check-clearance',()=>this.openClearance());on('section-cut',()=>this.toggleSection('x'));
    on('workshop-drawing',()=>{const o=this.getSelected();if(o)showDrawing(o);else this.toast('Seleccione una pieza para obtener su plano.');});
    on('export-json',()=>this.onExport());on('open-tutorial',()=>this.onTutorial());
    for(const type of ['slab','deck','mesh','negative'])on('floor-'+type,()=>this.createFloor(type));
    this.propsPanel.getClashes=e=>this.clashDetector.detect(e);this.propsPanel.onExplode=e=>this.toggleExploded(e);this.propsPanel.onSmartJoin=()=>this.openSmartConnection();
    const before=this.propsPanel.onPropertyChange;
    this.propsPanel.onPropertyChange=(e,meta)=>{this.rebuildJoints(e);this.syncPlateBolts(e);this.syncBoundWelds();this.sceneManager._applyVisualModeToObject(e);this.selectObject(e);before?.(e,meta);this.refresh();};
    const button=document.createElement('button');button.className='workshop-join-prompt hidden';button.textContent='＋ Añadir unión inteligente';button.onclick=()=>this.openSmartConnection();this.sceneManager.container.appendChild(button);this.suggestion=button;
    this.sceneManager.transformControls.addEventListener('objectChange',()=>this.updateSuggestion());
    return this;
  }
  updateSuggestion(){const beam=this.getSelected(),hit=beam?.type==='profile'&&this.sceneManager.objects.find(o=>findEncounter(o,beam,.15));this.suggestion?.classList.toggle('hidden',!hit);}
  commitConnection(column,beam,options={}){
    const c=cloneObject(column),b=cloneObject(beam);let result;
    try {result=buildSmartConnection(c,b,options);}catch(error){c._disposeMesh();b._disposeMesh();throw error;}
    const id=result.config.id;
    const previous=this.sceneManager.objects.filter(o=>o.params.smartJointOwner===beam.id&&o.params.assemblyId===id),ids=new Map();
    for(const part of result.parts){const old=previous.find(o=>(o.params.smartJointKey||o.params.role)===(part.params.smartJointKey||part.params.role));if(old){ids.set(part.id,old.id);part.restoreId(old.id);part.color=old.color;}}
    for(const part of result.parts){if(ids.has(part.params.hostPlateId))part.params.hostPlateId=ids.get(part.params.hostPlateId);if(part.params.boltGroup?.boltIds)part.params.boltGroup.boltIds=part.params.boltGroup.boltIds.map(id=>ids.get(id)||id);part._applyUserData();}
    this.sceneManager.objects.filter(o=>o.params.smartJointOwner===beam.id&&o.params.assemblyId===id).forEach(o=>this.sceneManager.removeObject(o));
    column.update(c.params);beam.update(b.params);beam.mesh.position.copy(b.mesh.position);beam.mesh.quaternion.copy(b.mesh.quaternion);beam.mesh.updateMatrixWorld(true);
    c._disposeMesh();b._disposeMesh();result.parts.forEach(p=>this.sceneManager.addObject(p));
    return result;
  }
  rebuildJoints(changed){if(this._rebuilding)return;this._rebuilding=true;try{for(const b of this.sceneManager.objects.filter(o=>o.params.smartJoint)){for(const config of b.params.smartJoints||[b.params.smartJoint]){if(changed.id!==b.id&&changed.id!==config.columnId)continue;const c=this.sceneManager.objects.find(o=>o.id===config.columnId);if(c)try{this.commitConnection(c,b,config);}catch(error){this.toast(`Unión pendiente de reajuste: ${error.message}`);}}}}finally{this._rebuilding=false;}}
  modal(title,body){document.querySelector('.workshop-modal')?.remove();const wrap=document.createElement('div');wrap.className='workshop-modal';wrap.innerHTML=`<section role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><h2>${title}</h2><button data-close aria-label="Cerrar">×</button></header><div class="workshop-modal-body">${body}</div></section>`;document.body.appendChild(wrap);wrap.querySelector('[data-close]').onclick=()=>wrap.remove();return wrap;}
  openSmartConnection(){
    const members=this.sceneManager.objects.filter(o=>o.type==='profile');
    const opts=members.map(o=>`<option value="${o.id}">${esc(o.params.role||o.designation)} · ${o.id}</option>`).join('');
    const wrap=this.modal('Unión inteligente',`<p>Encuentro viga–pilar I/H sobre ala. Genera chapa de testa, taladros, tornillos, cuatro rigidizadores y cartela siguiendo la pendiente.</p>${members.length>=2?`<form><label>Pilar<select name="column">${opts}</select></label><label>Viga<select name="beam">${opts}</select></label><div class="workshop-triplet"><label>Testa (mm)<input name="thickness" type="number" min="4" value="20" required></label><label>Holgura (mm)<input name="clearance" type="number" min="0" max="5" step=".1" value=".5" required></label><label>Borde (mm)<input name="edge" type="number" min="20" value="40" required></label></div><label>Pernos<select name="metric"><option>M16</option><option selected>M20</option><option>M24</option></select></label><label><input name="haunch" type="checkbox" checked> Cartela inferior ajustada</label><div class="workshop-notice">Ancho nominal del rigidizador: (b − tw) / 2. Se descuentan holguras y se recortan los acuerdos del perfil. Espesor igual al ala de la viga. Reglas geométricas editables.</div><div role="alert" class="workshop-error"></div><button type="submit" class="primary">Generar / actualizar unión</button></form>`:'<p>Hace falta un pilar y una viga próximos.</p>'}<button data-demo>Crear encuentro de práctica</button>`);
    wrap.querySelector('[data-demo]').onclick=()=>{wrap.remove();this.createPracticeNode();this.openSmartConnection();};
    const form=wrap.querySelector('form');if(!form)return;
    let pair=null;const selected=this.getSelected();for(const b of [selected,...members].filter(Boolean)){for(const c of members){if(findEncounter(c,b)){pair={c,b};break;}}if(pair)break;}
    if(pair){form.elements.column.value=pair.c.id;form.elements.beam.value=pair.b.id;}else form.elements.beam.selectedIndex=1;
    form.onsubmit=e=>{e.preventDefault();try{const c=members.find(o=>o.id===form.elements.column.value),b=members.find(o=>o.id===form.elements.beam.value);const result=this.commitConnection(c,b,{thicknessMm:Number(form.elements.thickness.value),clearanceMm:Number(form.elements.clearance.value),edgeMm:Number(form.elements.edge.value),diameter:Number(form.elements.metric.value.slice(1)),haunch:form.elements.haunch.checked});wrap.remove();this.selectObject(result.parts[0]);this.pushUndo();this.sceneManager.focusOnObject(result.parts[0]);this.toast(`Unión creada · ${result.parts.length} piezas · rigidizadores ${result.nominalStiffenerWidthMm.toFixed(1)} × ${result.thicknessMm} mm`);}catch(error){form.querySelector('.workshop-error').textContent=error.message;}};
  }
  createLesson(id,parameters,lesson){const existing=new THREE.Box3();this.sceneManager.objects.forEach(o=>existing.expandByObject(o.mesh));const commit=this.presetManager.onCommit;this.presetManager.onCommit=null;let parts;try{parts=this.presetManager.generate(id,parameters);}finally{this.presetManager.onCommit=commit;}if(!existing.isEmpty()){const own=new THREE.Box3();parts.forEach(o=>own.expandByObject(o.mesh));const dx=existing.max.x-own.min.x+1;parts.forEach(o=>{o.mesh.position.x+=dx;o.mesh.updateMatrixWorld(true);});}parts.forEach(o=>{o.params.lessonId=lesson.id;o.params.referenceStatus=lesson.referenceStatus;});this.pushUndo();this.refresh();this.sceneManager.fitAll();return parts;}
  createPracticeNode(){const bounds=new THREE.Box3();this.sceneManager.objects.forEach(o=>bounds.expandByObject(o.mesh));const x=bounds.isEmpty()?0:bounds.max.x+1;const c=new Profile('HEB','300',3,'column'),b=new Profile('IPE','300',2.8,'beam');c.params.role='Pilar del encuentro';b.params.role='Dintel del encuentro';c.setPosition(x,1.5,0);b.setPosition(x,2.4,1.55);this.sceneManager.addObject(c);this.sceneManager.addObject(b);this.selectObject(b);this.pushUndo();this.sceneManager.fitAll();}
  openClearance(){const selected=this.getSelection?.()||[];const objects=this.sceneManager.objects.filter(o=>o.mesh.visible&&o.type!=='weld');if(objects.length<2){this.toast('Necesita dos piezas para comprobar una holgura.');return;}const opts=objects.map(o=>`<option value="${o.id}">${esc(o.params.role||o.designation)} · ${o.id}</option>`).join('');const wrap=this.modal('Comprobar holgura',`<form><label>Primera pieza<select name="a">${opts}</select></label><label>Segunda pieza<select name="b">${opts}</select></label><label>Separación de montaje (mm)<input name="target" type="number" min="0" step=".1" value="10" required></label><button class="primary" type="submit">Medir separación real</button><div class="workshop-clearance-result" role="status"></div></form>`);const form=wrap.querySelector('form');form.elements.a.value=selected[0]?.id||objects[0].id;form.elements.b.value=selected[1]?.id||objects[1].id;form.onsubmit=e=>{e.preventDefault();const a=objects.find(o=>o.id===form.elements.a.value),b=objects.find(o=>o.id===form.elements.b.value),result=form.querySelector('[role=status]');if(a===b){result.textContent='Seleccione dos piezas distintas.';return;}const relation=solidRelation(a,b);if(relation.kind==='penetration'){result.textContent='Interferencia volumétrica detectada: una pieza penetra en la otra. Sepárelas antes de medir holgura.';return;}const r=surfaceDistance(a,b);if(!r){result.textContent='No hay superficies medibles.';return;}const distance=r.distance*1000,target=Number(form.elements.target.value);result.textContent=distance<.01?'Contacto o intersección entre superficies: 0 mm. Revise el encuentro.':`${distance.toFixed(2)} mm · objetivo ${target} mm · diferencia ${(distance-target).toFixed(2)} mm`;this.measureTool._createMeasurement(r.a,r.b);};}
  toggleSection(axis='x'){const renderer=this.sceneManager.renderer;if(this.sectionAxis===axis){renderer.clippingPlanes=[];this.sectionAxis=null;this.toast('Sección desactivada');return;}const selected=this.getSelected(),point=selected?.getPosition()||this.sceneManager.orbitControls.target;const normal=new THREE.Vector3(axis==='x'?1:0,axis==='y'?1:0,axis==='z'?1:0);renderer.clippingPlanes=[new THREE.Plane().setFromNormalAndCoplanarPoint(normal,point)];this.sectionAxis=axis;this.toast(`Corte ${axis.toUpperCase()} por el centro de la selección · repetir para salir`);}
  syncPlateBolts(plate){if(plate?.type!=='plate')return;plate.mesh.updateWorldMatrix(true,true);for(const bolt of this.sceneManager.objects.filter(o=>o.params.hostPlateId===plate.id&&o.params.hostLocal)){const m=FASTENER_METRICS[bolt.params.metric],p=bolt.params.hostLocal;p[2]=-plate.params.thickness/2-(m.nutH+m.washerT)/1000;bolt.update({shankLength:plate.params.thickness*1000+m.nutH+2*m.washerT});bolt.mesh.position.copy(new THREE.Vector3(...p).applyMatrix4(plate.mesh.matrixWorld));bolt.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1).transformDirection(plate.mesh.matrixWorld));bolt.mesh.updateMatrixWorld(true);}}
  syncBoundWelds(){const resolver=id=>this.sceneManager.objects.find(o=>o.id===id);this.sceneManager.objects.filter(o=>o.type==='weld').forEach(o=>o.updateFromBindings?.(resolver));}
  scanClashes(){const candidates=this.clashDetector.detectAll();const wrap=this.modal('Contactos e interferencias', '<p>Comprobación de superficies trianguladas. Los contactos se separan de las penetraciones detectadas.</p><div data-results role="status">Analizando…</div>');requestAnimationFrame(()=>{const results=[];for(const c of candidates){const a=c.first,b=c.second;if(!a||!b)continue;const r=solidRelation(a,b);if(r.kind==='penetration')results.push({a,b});}wrap.querySelector('[data-results]').innerHTML=results.length?results.map(r=>'<p>Interferencia: '+esc(r.a.params.role||r.a.designation)+' / '+esc(r.b.params.role||r.b.designation)+'</p>').join(''):'No se han encontrado penetraciones en las muestras de superficie analizadas.';});return candidates;}
  resetTransientState({refresh=true}={}){for(const saved of this.exploded.values())for(const[id,pos]of saved){const o=this.sceneManager.objects.find(o=>o.id===id);if(o){o.mesh.position.fromArray(pos);o.mesh.updateMatrixWorld(true);}}this.exploded.clear();this.syncBoundWelds();if(refresh)this.refresh();}
  toggleExploded(element){const id=element?.params.assemblyId||element?.params.templateInstanceId;if(!id){this.toast('Seleccione una pieza de un conjunto.');return;}if(this.exploded.has(id)){this.resetTransientState();return;}const parts=this.sceneManager.objects.filter(o=>o.params.assemblyId===id||o.params.templateInstanceId===id);const positions=new Map(parts.map(o=>[o.id,o.mesh.position.toArray()])),center=parts.reduce((p,o)=>p.add(o.mesh.position),new THREE.Vector3()).divideScalar(parts.length);parts.forEach((o,i)=>{const direction=o.mesh.position.clone().sub(center);if(direction.length()<.001)direction.set(i%2?1:-1,.3,0);o.mesh.position.addScaledVector(direction.normalize(),.2+(i%4)*.06);o.mesh.updateMatrixWorld(true);});this.exploded.set(id,positions);this.toast('Despiece temporal · guardar recompone el conjunto');}
  createFloor(type){const id=`floor-${Date.now()}`,parts=[],box=new THREE.Box3();this.sceneManager.objects.forEach(o=>box.expandByObject(o.mesh));const x=box.isEmpty()?0:box.max.x+1.6;
    if(type==='slab'){const p=new Plate('base',3,4,.12,{category:'floor',role:'Losa · 3000 × 4000 × 120 mm'});p.mesh.rotation.x=-Math.PI/2;p.setPosition(x,.06,0);parts.push(p);}
    if(type==='deck'){for(let i=0;i<24;i++){const width=.125,rise=i%2?.035:-.035,length=Math.hypot(width,rise),p=new Plate('gusset-square',length,4,.001,{category:'floor',role:`Chapa grecada · paño ${i+1}`});p.mesh.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(new THREE.Vector3(width,rise,0).normalize(),new THREE.Vector3(0,0,1),new THREE.Vector3(rise,-width,0).normalize()));p.setPosition(x-1.5+(i+.5)*width,.1,0);parts.push(p);}}
    if(type==='mesh'){for(let axis=0;axis<2;axis++)for(let i=0;i<16;i++){const p=new Reinforcement({diameterMm:10,length:3,role:`Malla ${axis?'X':'Z'} · barra ${i+1}`});p.mesh.rotation.y=axis?Math.PI/2:0;p.setPosition(x+(axis?0:-1.5+i*.2),.1+axis*.01,axis?-1.5+i*.2:0);parts.push(p);}}
    if(type==='negative'){for(const z of [-.15,.15]){const p=new Reinforcement({diameterMm:12,length:2,role:'Armadura de negativos',points:[[-1,0,0],[-.65,.15,0],[.65,.15,0],[1,0,0]]});p.setPosition(x,.1,z);parts.push(p);}}
    parts.forEach(o=>{o.params.assemblyId=id;this.sceneManager.addObject(o);});this.selectObject(parts[0]);this.pushUndo();this.sceneManager.fitAll();this.toast(`${parts.length} componentes de forjado creados`);
  }
}
